### ISSUE TITLE
[BUG][問題查找]tidebit.com系統異常crash

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1159]
線索1：
```
[2023-01-05T01:32:02.864Z][ExchangeHub]!!!ERROR postCancelOrder [memberId(26701)] updateOrderStatus出錯 body { orderId: '404255636', 'X-CSRF-Token': null } dbOrder {
  id: 404255636,
  bid: 34,
  ask: 3,
  currency: 202,
  price: '1228.0000000000000000',
  volume: '3.0000000000000000',
  origin_volume: '3.0000000000000000',
  state: 0,
  done_at: null,
  type: 'OrderBid',
  member_id: 26701,
  created_at: 2023-01-05T01:07:34.000Z,
  updated_at: 2023-01-05T01:29:05.000Z,
  sn: null,
  source: 'Web',
  ord_type: 'limit',
  locked: '3684.0000000000000000',
  origin_locked: '3684.0000000000000000',
  funds_received: '0.0000000000000000',
  trades_count: 0
}

```

線索2：連續重啟造成系統的 crash，造成連線重啟的原因不明
```
[1m[32mDB[0m[21m tidebitpro connect success
[1/5/2023, 1:59:03 AM][Websocket] this.ws.onopen: this.urlwss://pusher.tinfo.top:443/app/2b78567f96a2c0f40368?protocol=7&client=js&version=2.2.0&flash=false
[1/5/2023, 1:59:04 AM][Websocket] this.ws.onopen: this.urlwss://ws.okx.com:8443/ws/v5/public
[1/5/2023, 1:59:04 AM][Websocket] this.ws.onopen: this.urlwss://ws.okx.com:8443/ws/v5/private
[1m[32mHTTP [0m[21m  http://127.0.0.1:80
[1m[32mHTTPS[0m[21m  https://127.0.0.1:443
[1:59:04 AM][ExchangeHubService] _syncOuterTrades(exchange:OKEx, interval:604800000, clOrdId:undefined) apiOuterTrades.length:[3] needProcessTrades.length:[0]
[1:59:04 AM][ExchangeHubService] syncUnProcessedOuterTrades(exchange:OKEx outerTrades.length:[0] []
[2:08:50 AM][DepthBook: DepthBook] updateAll(lotSz:0.0001, instId:ETC-USDC) error TypeError: Cannot read property 'lotSz' of undefined
    at DepthBook.updateAll (/home/okex/workspace/TideBitEx/backend/libs/Books/DepthBook.js:264:33)
    at TibeBitConnector._updateBooks (/home/okex/workspace/TideBitEx/backend/libs/Connectors/TideBitConnector.js:403:20)
    at WebSocket.tidebitWsEventListener (/home/okex/workspace/TideBitEx/backend/libs/Connectors/TideBitConnector.js:153:16)
    at WebSocket.onMessage (/home/okex/workspace/TideBitEx/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/home/okex/workspace/TideBitEx/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/home/okex/workspace/TideBitEx/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/okex/workspace/TideBitEx/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/okex/workspace/TideBitEx/node_modules/ws/lib/receiver.js:148:22) { asks: [], bids: [] }
[1m[32mDB[0m[21m tidebitpro connect success
[1/5/2023, 2:08:52 AM][Websocket] this.ws.onopen: this.urlwss://pusher.tinfo.top:443/app/2b78567f96a2c0f40368?protocol=7&client=js&version=2.2.0&flash=false
[1/5/2023, 2:08:52 AM][Websocket] this.ws.onopen: this.urlwss://ws.okx.com:8443/ws/v5/public
[1/5/2023, 2:08:52 AM][Websocket] this.ws.onopen: this.urlwss://ws.okx.com:8443/ws/v5/private
[1m[32mHTTP [0m[21m  http://127.0.0.1:80
[1m[32mHTTPS[0m[21m  https://127.0.0.1:443
[2:08:52 AM][ExchangeHubService] _syncOuterTrades(exchange:OKEx, interval:604800000, clOrdId:undefined) apiOuterTrades.length:[3] needProcessTrades.length:[0]
[2:08:52 AM][ExchangeHubService] syncUnProcessedOuterTrades(exchange:OKEx outerTrades.length:[0] []
[2:08:54 AM][DepthBook: DepthBook] updateAll(lotSz:0.0001, instId:ETC-USDC) error TypeError: Cannot read property 'lotSz' of undefined
    at DepthBook.updateAll (/home/okex/workspace/TideBitEx/backend/libs/Books/DepthBook.js:264:33)
    at TibeBitConnector._updateBooks (/home/okex/workspace/TideBitEx/backend/libs/Connectors/TideBitConnector.js:403:20)
    at WebSocket.tidebitWsEventListener (/home/okex/workspace/TideBitEx/backend/libs/Connectors/TideBitConnector.js:153:16)
    at WebSocket.onMessage (/home/okex/workspace/TideBitEx/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/home/okex/workspace/TideBitEx/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/home/okex/workspace/TideBitEx/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/okex/workspace/TideBitEx/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/okex/workspace/TideBitEx/node_modules/ws/lib/receiver.js:148:22) { asks: [], bids: [] }
[1m[32mDB[0m[21m tidebitpro connect success
[1/5/2023, 2:08:55 AM][Websocket] this.ws.onopen: this.urlwss://pusher.tinfo.top:443/app/2b78567f96a2c0f40368?protocol=7&client=js&version=2.2.0&flash=false
[1/5/2023, 2:08:55 AM][Websocket] this.ws.onopen: this.urlwss://ws.okx.com:8443/ws/v5/public
[1/5/2023, 2:08:56 AM][Websocket] this.ws.onopen: this.urlwss://ws.okx.com:8443/ws/v5/private
[2:08:56 AM][ExchangeHubService] _syncOuterTrades(exchange:OKEx, interval:604800000, clOrdId:undefined) apiOuterTrades.length:[3] needProcessTrades.length:[0]
[2:08:56 AM][ExchangeHubService] syncUnProcessedOuterTrades(exchange:OKEx outerTrades.length:[0] []
[1m[32mHTTP [0m[21m  http://127.0.0.1:80
[1m[32mHTTPS[0m[21m  https://127.0.0.1:443
[2:08:57 AM][DepthBook: DepthBook] updateAll(lotSz:0.0001, instId:ETC-USDC) error TypeError: Cannot read property 'lotSz' of undefined
    at DepthBook.updateAll (/home/okex/workspace/TideBitEx/backend/libs/Books/DepthBook.js:264:33)
    at TibeBitConnector._updateBooks (/home/okex/workspace/TideBitEx/backend/libs/Connectors/TideBitConnector.js:403:20)
    at WebSocket.tidebitWsEventListener (/home/okex/workspace/TideBitEx/backend/libs/Connectors/TideBitConnector.js:153:16)
    at WebSocket.onMessage (/home/okex/workspace/TideBitEx/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/home/okex/workspace/TideBitEx/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/home/okex/workspace/TideBitEx/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/okex/workspace/TideBitEx/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/okex/workspace/TideBitEx/node_modules/ws/lib/receiver.js:148:22) { asks: [], bids: [] }
```

**Comment by TzuHanLiang** [comment]
- take 2hrs 監測 tidebit.com
- 0.5 先把 `fix read property "lotSz" of undefined` 改掉

**Comment by TzuHanLiang** [comment]
- 調整成 v0.8.23.2 crash 頻率有降低（還是會 crash）需要繼續觀察

**Comment by TzuHanLiang** [comment]
- 今日觀察 5hrs 內均無再手動重啟

**Comment by Julian0701** [comment]
於 [TBETC000003_使用者介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000003/20230119.md) 驗證通過

**Comment by TzuHanLiang** [comment]
- 2023/03/08 14:30-17:30 take 3hrs 觀察沒有 crash

**Comment by TzuHanLiang** [comment]
8:01 ws 連線異常造成 crash
<img width="947" alt="Screenshot 2023-03-13 at 8 34 29 AM" src="https://user-images.githubusercontent.com/17249354/224591997-bcc59720-d94b-4cc1-a4ea-c5bb5de825c5.png">

**Comment by TzuHanLiang** [comment]
> 8:01 ws 連線異常造成 crash
> 
> <img alt="Screenshot 2023-03-13 at 8 34 29 AM" width="947" src="https://user-images.githubusercontent.com/17249354/224591997-bcc59720-d94b-4cc1-a4ea-c5bb5de825c5.png">

這邊應該不是crash 而只是 websocket 重連，系統重啟的log看起來應該如下圖所示
<img width="798" alt="Screenshot 2023-03-13 at 10 14 27" src="https://user-images.githubusercontent.com/17249354/224593051-920195ca-8ab4-43d1-a487-dd27ca48714f.png">
