### ISSUE TITLE
[BUG] Tidebit 市價單掛單後沒有更新 Close Order

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#829]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於限價單買進的第二欄位等於市價深度的 amount 
4.  點擊買進
5.  掛單成功
6.  Close Order 無顯示

影響範圍： Tidebit Trading - 市價買進賣出

發現可能是沒有撮合成功

![](https://i.imgur.com/dAi3PWn.png)
![](https://i.imgur.com/JKCYX5S.png)

**Comment by TzuHanLiang** [comment]
出錯的原因為
```
I, [2022-09-06T07:47:03.557068 #2769]  INFO -- : btchkd 2022-09-06 07:17:03 there're very old orders matched, need human intervention
F, [2022-09-06T07:47:03.557344 #2769] FATAL -- : all engine failed to start. Matched during dryrun:
I, [2022-09-06T07:47:03.557400 #2769]  INFO -- : {:market_id=>"btchkd", :ask_id=>417, :bid_id=>344, :strike_price=>#<BigDecimal:7f548c28b8c8,'0.1E3',9(18)>, :volume=>#<BigDecimal:7f548c28b7d8,'0.4999E0',9(18)>, :funds=>#<BigDecimal:7f548bcc3198,'0.4999E2',18(27)>}
I, [2022-09-06T07:47:03.557442 #2769]  INFO -- : {:market_id=>"btchkd", :ask_id=>357, :bid_id=>419, :strike_price=>#<BigDecimal:7f548bcbfd68,'0.11E3',9(18)>, :volume=>#<BigDecimal:7f548bcbfc28,'0.1E-3',9(18)>, :funds=>#<BigDecimal:7f548c289fa0,'0.11E-1',9(27)>}
I, [2022-09-06T07:47:03.557478 #2769]  INFO -- : {:market_id=>"btchkd", :ask_id=>470, :bid_id=>469, :strike_price=>#<BigDecimal:7f548bc8ade8,'0.1E3',9(18)>, :volume=>#<BigDecimal:7f548bc8ac80,'0.5E0',9(18)>, :funds=>#<BigDecimal:7f548cf21538,'0.5E2',9(27)>}
```

時間延長後
```
/home/ubuntu/TideBit-Lagacy/app/models/matching/order_book_manager.rb:13:in `build_order': Missing ord_type: {:id=>435, :market=>"ethusdt", :type=>:ask, :ord_type=>nil, :volume=>#<BigDecimal:7fbd98a45648,'0.1E-2',9(18)>, :price=>#<BigDecimal:7fbd98a45580,'0.159227E4',18(27)>, :locked=>#<BigDecimal:7fbd98a453a0,'0.1E-2',9(18)>, :timestamp=>1662106266} (ArgumentError)
	from /home/ubuntu/TideBit-Lagacy/app/models/worker/matching.rb:64:in `build_order'
	from /home/ubuntu/TideBit-Lagacy/app/models/worker/matching.rb:80:in `block in load_orders'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
	from /home/ubuntu/TideBit-Lagacy/app/models/worker/matching.rb:79:in `load_orders'
	from /home/ubuntu/TideBit-Lagacy/app/models/worker/matching.rb:69:in `initialize_engine'
	from /home/ubuntu/TideBit-Lagacy/app/models/worker/matching.rb:47:in `block in reload'
	from /home/ubuntu/TideBit-Lagacy/app/models/worker/matching.rb:47:in `each'
	from /home/ubuntu/TideBit-Lagacy/app/models/worker/matching.rb:47:in `reload'
	from /home/ubuntu/TideBit-Lagacy/app/models/worker/matching.rb:19:in `initialize'
```
<img width="451" alt="Screen Shot 2022-09-06 at 16 21 23" src="https://user-images.githubusercontent.com/17249354/188585938-c6b245f4-6324-49b9-961a-a65b5688d12f.png">
這個為 eth-usdt 的 ioc 交易狀態在 100 （waiting） 此為不應該出現的狀態，是先前我為了再現 #822 而特意做的交易（為特殊情況）

**Comment by TzuHanLiang** [comment]
<img width="451" alt="Screen Shot 2022-09-06 at 16 32 23" src="https://user-images.githubusercontent.com/17249354/188587216-11ab7a38-3dc9-4580-9af1-bd1f4cf72a28.png">

**Comment by TzuHanLiang** [comment]
解法： 把不該存在的這兩筆交易的state 改成0

**Comment by TzuHanLiang** [comment]
take 2.5hrs

**Comment by royal0721** [comment]
20220908 測試有更新 Depthbook 但 Close order 需要刷新才會更新
![](https://i.imgur.com/siwAHcn.png)
![](https://i.imgur.com/dKLIXKy.png)
![](https://i.imgur.com/qN4oqN3.png)
![](https://i.imgur.com/9nV42n6.png)

**Comment by royal0721** [comment]
20220912 測試未重現

掛單前
<img width="1440" alt="Screen Shot 2022-09-12 at 4 51 45 PM" src="https://user-images.githubusercontent.com/29693123/189612675-4738c23f-5d51-4b65-97b1-4fd6dacb2a2a.png">
掛單後
<img width="1440" alt="Screen Shot 2022-09-12 at 4 51 49 PM" src="https://user-images.githubusercontent.com/29693123/189612689-e45204ec-a742-4970-ac81-7f853a30eb8f.png">
