### ISSUE TITLE
[BUG] websocket 異常斷線

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#983]
![Image](https://user-images.githubusercontent.com/17249354/198944006-dcd92122-ad80-44da-a9c7-4dae64246cae.png)

週五至週六每小時會斷兩次，與重開無關

**Comment by TzuHanLiang** [comment]
When a WebSocket connection is closed without a "close frame", the pusher-js library emits an error with code 1006. Usually this is caused by WebSocket-incompatible proxies, which can't close the connection in the correct way.

[rel](https://support.pusher.com/hc/en-us/articles/4412491141265-What-Is-Meant-By-Channels-Error-1006-#:~:text=When%20a%20WebSocket%20connection%20is,connection%20in%20the%20correct%20way.)

**Comment by TzuHanLiang** [comment]
```
this.ws.on("error") RangeError: Invalid WebSocket frame: invalid status code 60015
    at Receiver.controlMessage (/home/ubuntu/workspace/TideBitEx/node_modules/ws/lib/receiver.js:561:18)
    at Receiver.getData (/home/ubuntu/workspace/TideBitEx/node_modules/ws/lib/receiver.js:429:42)
    at Receiver.startLoop (/home/ubuntu/workspace/TideBitEx/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/ubuntu/workspace/TideBitEx/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.socketOnData (/home/ubuntu/workspace/TideBitEx/node_modules/ws/lib/websocket.js:1192:35)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9) {
  code: 'WS_ERR_INVALID_CLOSE_CODE',
  [Symbol(status-code)]: 1002
}
[WebSocket][close] Connection died event 1006
```

**Comment by TzuHanLiang** [comment]
<img width="1680" alt="Screen Shot 2022-12-09 at 10 50 34" src="https://user-images.githubusercontent.com/17249354/206613274-a500597f-ddf1-4cee-b792-44701d3e930a.png">

**Comment by TzuHanLiang** [comment]
> <img alt="Screen Shot 2022-12-09 at 10 50 34" width="1680" src="https://user-images.githubusercontent.com/17249354/206613274-a500597f-ddf1-4cee-b792-44701d3e930a.png">

經測試此問題造成的斷線重連機制沒有問題，這個 bug 不會導致 ws 停下來。

**Comment by TzuHanLiang** [comment]
- getMemberByCondition 當參數為 refer_code 時會出錯，這邊出錯後 processor 也會跳錯，最終會出現 ws 停止，目前將 getMemberByCondition 的 錯誤先修正

**Comment by TzuHanLiang** [comment]
- registerMarket 不完善，前端 _getTrades() 會出錯

**Comment by TzuHanLiang** [comment]
- take 4hrs

**Comment by Julian0701** [comment]
使用 [TBETC000011](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000011_%20WebSocket%20%E9%A0%BB%E5%AF%AC%E4%BD%BF%E7%94%A8%E6%83%85%E5%BD%A2.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000011](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000011/20221216.md) 驗證通過
沒有異常斷線發生
